# Generated by Django 5.0.1 on 2024-02-01 11:53

import application1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnyFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('some_name', models.CharField(max_length=50, unique=True)),
                ('image', application1.models.YandexImageField(storage=application1.models.YandexStorage(), upload_to=application1.models.user_directory_path_by_images)),
                ('file', application1.models.YandexFileField(storage=application1.models.YandexStorage(), upload_to=application1.models.user_directory_path_by_files)),
            ],
        ),
    ]
