# Generated by Django 5.0.1 on 2024-01-30 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import application1.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Any_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('some_name', models.CharField(max_length=50, unique=True)),
                ('image', models.ImageField(unique=True, upload_to=application1.models.user_directory_path_by_images)),
                ('file', models.FileField(unique=True, upload_to=application1.models.user_directory_path_by_files)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                           to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
