# Generated by Django 5.0.1 on 2024-02-01 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application1', '0002_anyfile_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anyfile',
            name='user_id',
        ),
    ]
