# Generated by Django 5.0.1 on 2024-01-31 09:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application1', '0002_alter_any_file_file_alter_any_file_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Any_file',
            new_name='AnyFile',
        ),
    ]
