# Generated by Django 5.0.1 on 2024-01-31 15:29

import application1.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application1', '0003_rename_any_file_anyfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anyfile',
            name='file',
            field=application1.models.YandexFileField(storage=application1.models.YandexStorage(), upload_to=application1.models.user_directory_path_by_files),
        ),
        migrations.AlterField(
            model_name='anyfile',
            name='image',
            field=application1.models.YandexImageField(storage=application1.models.YandexStorage(), upload_to=application1.models.user_directory_path_by_images),
        ),
    ]
